
disabled_rules:
- line_length
- identifier_name
- unused_optional_binding
- trailing_whitespace
- vertical_whitespace

opt_in_rules:
- indentation_width
- literal_expression_end_indentation
- closure_end_indentation
- closing_brace

included:

excluded:
- Pods
- /DiaryApp/Model/CardManager.swift
